name: voco_app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.10
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
